export type SkillAction = {
  name: string;
  xp: number;
  level?: number;
  category?: string;
  itemName?: string;
  materials?: Array<{
    itemName: string;
    quantity: number;
  }>;
  notes?: string;
};

export type SkillActionGroup = {
  skill: string;
  actions: SkillAction[];
};

const COMBAT_MELEE = [
  { name: 'Shared melee training', xp: 4, notes: 'Per damage dealt' },
  { name: 'Sand Crab', xp: 240, notes: 'Approx. per kill' },
  { name: 'Ammonite Crab', xp: 400, notes: 'Approx. per kill' },
  { name: 'Experiments', xp: 400, notes: 'Approx. per kill' },
  { name: 'Slayer monster', xp: 600, notes: 'Example per kill' },
  { name: 'Nightmare Zone absorption hour', xp: 70_000 },
  { name: 'Pest Control novice point', xp: 350 },
  { name: 'Pest Control veteran point', xp: 700 }
];

export const SKILL_ORDER = [
  'Prayer',
  'Cooking',
  'Woodcutting',
  'Fletching',
  'Fishing',
  'Firemaking',
  'Crafting',
  'Smithing',
  'Mining',
  'Herblore',
  'Agility',
  'Thieving',
  'Slayer',
  'Farming',
  'Runecraft',
  'Hunter',
  'Construction',
  'Sailing'
];

const PRAYER_BONES = [
  { name: 'Bones', xp: 4.5 },
  { name: 'Wolf bones', xp: 4.5 },
  { name: 'Burnt bones', xp: 4.5 },
  { name: 'Monkey bones', xp: 5 },
  { name: 'Bat bones', xp: 5.3 },
  { name: 'Big bones', xp: 15 },
  { name: 'Jogre bones', xp: 15 },
  { name: 'Zogre bones', xp: 22.5 },
  { name: 'Shaikahan bones', xp: 25 },
  { name: 'Baby dragon bones', xp: 30 },
  { name: 'Wyrm bones', xp: 50 },
  { name: 'Wyvern bones', xp: 72 },
  { name: 'Dragon bones', xp: 72 },
  { name: 'Drake bones', xp: 80 },
  { name: 'Fayrg bones', xp: 84 },
  { name: 'Raurg bones', xp: 96 },
  { name: 'Hydra bones', xp: 110 },
  { name: 'Dagannoth bones', xp: 125 },
  { name: 'Ourg bones', xp: 140 },
  { name: 'Superior dragon bones', xp: 150 }
];

const PRAYER_ACTIONS = [
  ...PRAYER_BONES.map((bone) => ({
    ...bone,
    level: 1,
    category: 'Bones',
    itemName: bone.name
  })),
  { name: 'Ensouled goblin head', xp: 130, level: 1, category: 'Ensouled heads', itemName: 'Ensouled goblin head' },
  { name: 'Ensouled monkey head', xp: 182, level: 1, category: 'Ensouled heads', itemName: 'Ensouled monkey head' },
  { name: 'Ensouled imp head', xp: 286, level: 1, category: 'Ensouled heads', itemName: 'Ensouled imp head' },
  { name: 'Ensouled minotaur head', xp: 364, level: 1, category: 'Ensouled heads', itemName: 'Ensouled minotaur head' },
  { name: 'Ensouled scorpion head', xp: 454, level: 1, category: 'Ensouled heads', itemName: 'Ensouled scorpion head' },
  { name: 'Ensouled bear head', xp: 480, level: 1, category: 'Ensouled heads', itemName: 'Ensouled bear head' },
  { name: 'Ensouled unicorn head', xp: 494, level: 1, category: 'Ensouled heads', itemName: 'Ensouled unicorn head' },
  { name: 'Ensouled dog head', xp: 520, level: 1, category: 'Ensouled heads', itemName: 'Ensouled dog head' },
  { name: 'Ensouled chaos druid head', xp: 584, level: 1, category: 'Ensouled heads', itemName: 'Ensouled chaos druid head' },
  { name: 'Ensouled giant head', xp: 650, level: 1, category: 'Ensouled heads', itemName: 'Ensouled giant head' },
  { name: 'Ensouled ogre head', xp: 716, level: 1, category: 'Ensouled heads', itemName: 'Ensouled ogre head' },
  { name: 'Ensouled elf head', xp: 754, level: 1, category: 'Ensouled heads', itemName: 'Ensouled elf head' },
  { name: 'Ensouled troll head', xp: 780, level: 1, category: 'Ensouled heads', itemName: 'Ensouled troll head' },
  { name: 'Ensouled horror head', xp: 832, level: 1, category: 'Ensouled heads', itemName: 'Ensouled horror head' },
  { name: 'Ensouled kalphite head', xp: 884, level: 1, category: 'Ensouled heads', itemName: 'Ensouled kalphite head' },
  { name: 'Ensouled dagannoth head', xp: 936, level: 1, category: 'Ensouled heads', itemName: 'Ensouled dagannoth head' },
  { name: 'Ensouled bloodveld head', xp: 1040, level: 1, category: 'Ensouled heads', itemName: 'Ensouled bloodveld head' },
  { name: 'Ensouled TzHaar head', xp: 1104, level: 1, category: 'Ensouled heads', itemName: 'Ensouled tzhaar head' },
  { name: 'Ensouled demon head', xp: 1170, level: 1, category: 'Ensouled heads', itemName: 'Ensouled demon head' },
  { name: 'Ensouled aviansie head', xp: 1234, level: 1, category: 'Ensouled heads', itemName: 'Ensouled aviansie head' },
  { name: 'Ensouled abyssal head', xp: 1300, level: 1, category: 'Ensouled heads', itemName: 'Ensouled abyssal head' },
  { name: 'Ensouled dragon head', xp: 1560, level: 1, category: 'Ensouled heads', itemName: 'Ensouled dragon head' },
  { name: 'Offering bird egg', xp: 100, level: 1, category: 'Offerings', itemName: 'Bird egg' },
  { name: 'Demonic ashes', xp: 10, level: 1, category: 'Ashes', itemName: 'Demonic ashes' },
  { name: 'Vile ashes', xp: 25, level: 1, category: 'Ashes', itemName: 'Vile ashes' },
  { name: 'Malicious ashes', xp: 65, level: 1, category: 'Ashes', itemName: 'Malicious ashes' },
  { name: 'Abyssal ashes', xp: 85, level: 1, category: 'Ashes', itemName: 'Abyssal ashes' },
  { name: 'Infernal ashes', xp: 110, level: 1, category: 'Ashes', itemName: 'Infernal ashes' }
];

export const SKILL_ACTIONS: SkillActionGroup[] = [
  { skill: 'Attack', actions: COMBAT_MELEE },
  { skill: 'Strength', actions: COMBAT_MELEE },
  { skill: 'Defence', actions: COMBAT_MELEE },
  {
    skill: 'Hitpoints',
    actions: [
      { name: 'Combat damage', xp: 1.33, notes: 'Per damage dealt' },
      { name: 'Sand Crab kill', xp: 80 },
      { name: 'Ammonite Crab kill', xp: 133 },
      { name: 'Slayer monster kill', xp: 200 },
      { name: 'Nightmare Zone hour', xp: 23_000 },
      { name: 'Pest Control novice point', xp: 116 },
      { name: 'Pest Control veteran point', xp: 233 }
    ]
  },
  {
    skill: 'Ranged',
    actions: [
      { name: 'Ranged damage', xp: 4, notes: 'Per damage dealt' },
      { name: 'Cannonball damage', xp: 2, notes: 'Per damage dealt' },
      { name: 'Sand Crab kill', xp: 240 },
      { name: 'Ammonite Crab kill', xp: 400 },
      { name: 'Chinchompa throw', xp: 160, notes: 'Varies by targets hit' },
      { name: 'Red chinchompa throw', xp: 220, notes: 'Varies by targets hit' },
      { name: 'Black chinchompa throw', xp: 280, notes: 'Varies by targets hit' },
      { name: 'Nightmare Zone hour', xp: 75_000 }
    ]
  },
  {
    skill: 'Prayer',
    actions: PRAYER_ACTIONS
  },
  {
    skill: 'Magic',
    actions: [
      { name: 'Wind Strike cast', xp: 5.5 },
      { name: 'Water Strike cast', xp: 7.5 },
      { name: 'Earth Strike cast', xp: 9.5 },
      { name: 'Fire Strike cast', xp: 11.5 },
      { name: 'Wind Bolt cast', xp: 13.5 },
      { name: 'Water Bolt cast', xp: 16.5 },
      { name: 'Earth Bolt cast', xp: 19.5 },
      { name: 'Fire Bolt cast', xp: 22.5 },
      { name: 'Wind Blast cast', xp: 25.5 },
      { name: 'Water Blast cast', xp: 28.5 },
      { name: 'Earth Blast cast', xp: 31.5 },
      { name: 'Fire Blast cast', xp: 34.5 },
      { name: 'Wind Wave cast', xp: 36 },
      { name: 'Water Wave cast', xp: 37.5 },
      { name: 'Earth Wave cast', xp: 40 },
      { name: 'Fire Wave cast', xp: 42.5 },
      { name: 'Wind Surge cast', xp: 44 },
      { name: 'Water Surge cast', xp: 46 },
      { name: 'Earth Surge cast', xp: 48 },
      { name: 'Fire Surge cast', xp: 50.5 },
      { name: 'Low Level Alchemy cast', xp: 31 },
      { name: 'High Level Alchemy cast', xp: 65 },
      { name: 'Superheat Item cast', xp: 53 },
      { name: 'Varrock Teleport cast', xp: 35 },
      { name: 'Lumbridge Teleport cast', xp: 41 },
      { name: 'Falador Teleport cast', xp: 48 },
      { name: 'Camelot Teleport cast', xp: 55.5 },
      { name: 'Ardougne Teleport cast', xp: 61 },
      { name: 'Watchtower Teleport cast', xp: 68 },
      { name: 'Bones to Peaches cast', xp: 35.5 },
      { name: 'Enchant sapphire jewellery', xp: 17.5 },
      { name: 'Enchant emerald jewellery', xp: 37 },
      { name: 'Enchant ruby jewellery', xp: 59 },
      { name: 'Enchant diamond jewellery', xp: 67 },
      { name: 'Enchant onyx jewellery', xp: 97 },
      { name: 'Enchant zenyte jewellery', xp: 110 },
      { name: 'Telekinetic Grab cast', xp: 43 },
      { name: 'Stun cast', xp: 90 },
      { name: 'Humidify cast', xp: 65 },
      { name: 'Ice Burst cast', xp: 22, notes: 'Base cast XP' },
      { name: 'Blood Burst cast', xp: 33, notes: 'Base cast XP' },
      { name: 'Ice Barrage cast', xp: 52, notes: 'Base cast XP' },
      { name: 'Blood Barrage cast', xp: 51, notes: 'Base cast XP' },
      { name: 'Plank Make cast', xp: 90 },
      { name: 'String Jewellery cast', xp: 83 }
    ]
  },
  {
    skill: 'Cooking',
    actions: [
      { name: 'Cooked meat', xp: 30, level: 1, category: 'Meat' },
      { name: 'Cooked chicken', xp: 30, level: 1, category: 'Meat' },
      { name: 'Cooked rabbit', xp: 30, level: 1, category: 'Meat' },
      { name: 'Roast bird meat', xp: 62.5, level: 11, category: 'Meat' },
      { name: 'Roast beast meat', xp: 82.5, level: 21, category: 'Meat' },
      { name: 'Cooked chompy', xp: 140, level: 30, category: 'Meat' },
      { name: 'Jubbly', xp: 160, level: 41, category: 'Meat' },
      { name: 'Bread', xp: 40, level: 1, category: 'Baking' },
      { name: 'Shrimp', xp: 30 },
      { name: 'Sardine', xp: 40 },
      { name: 'Herring', xp: 50 },
      { name: 'Anchovies', xp: 30 },
      { name: 'Mackerel', xp: 60, level: 10, category: 'Fish' },
      { name: 'Cod', xp: 75, level: 18, category: 'Fish' },
      { name: 'Trout', xp: 70 },
      { name: 'Salmon', xp: 90 },
      { name: 'Tuna', xp: 100 },
      { name: 'Bass', xp: 130, level: 43, category: 'Fish' },
      { name: 'Karambwan', xp: 190 },
      { name: 'Lobster', xp: 120 },
      { name: 'Swordfish', xp: 140 },
      { name: 'Cave eel', xp: 115, level: 38, category: 'Fish' },
      { name: 'Lava eel', xp: 30, level: 53, category: 'Fish' },
      { name: 'Sweetcorn', xp: 104, level: 28, category: 'Vegetables' },
      { name: 'Potato with cheese', xp: 40 },
      { name: 'Curry', xp: 280 },
      { name: 'Ugthanki kebab', xp: 120 },
      { name: 'Monkfish', xp: 150 },
      { name: 'Shark', xp: 210 },
      { name: 'Sea turtle', xp: 211.3 },
      { name: 'Manta ray', xp: 216.3 },
      { name: 'Anglerfish', xp: 230 },
      { name: 'Dark crab', xp: 215 },
      { name: 'Plain pizza', xp: 143 },
      { name: 'Meat pizza', xp: 169, level: 45, category: 'Pizza' },
      { name: 'Anchovy pizza', xp: 182, level: 55, category: 'Pizza' },
      { name: 'Pineapple pizza', xp: 182 },
      { name: 'Tuna potato', xp: 309.5 },
      { name: 'Jug of wine', xp: 200 },
      { name: 'Redberry pie', xp: 78, level: 10, category: 'Pie' },
      { name: 'Meat pie', xp: 110, level: 20, category: 'Pie' },
      { name: 'Mud pie', xp: 128, level: 29, category: 'Pie' },
      { name: 'Apple pie', xp: 130, level: 30, category: 'Pie' },
      { name: 'Garden pie', xp: 138, level: 34, category: 'Pie' },
      { name: 'Fish pie', xp: 164, level: 47, category: 'Pie' },
      { name: 'Admiral pie', xp: 210, level: 70, category: 'Pie' },
      { name: 'Wild pie', xp: 240, level: 85, category: 'Pie' },
      { name: 'Summer pie', xp: 260, level: 95, category: 'Pie' },
      { name: 'Stew', xp: 117, level: 25, category: 'Stew' },
      { name: 'Spicy stew', xp: 117, level: 25, category: 'Stew' },
      { name: 'Cake', xp: 180 },
      { name: 'Chocolate cake', xp: 210 }
    ]
  },
  {
    skill: 'Woodcutting',
    actions: [
      { name: 'Logs', xp: 25 },
      { name: 'Achey tree logs', xp: 25 },
      { name: 'Oak logs', xp: 37.5 },
      { name: 'Willow logs', xp: 67.5 },
      { name: 'Teak logs', xp: 85 },
      { name: 'Maple logs', xp: 100 },
      { name: 'Hollow tree bark', xp: 82.5 },
      { name: 'Mahogany logs', xp: 125 },
      { name: 'Arctic pine logs', xp: 140.2 },
      { name: 'Yew logs', xp: 175 },
      { name: 'Magic logs', xp: 250 },
      { name: 'Redwood logs', xp: 380 },
      { name: 'Blisterwood logs', xp: 76 },
      { name: 'Sulliuscep cap', xp: 127 },
      { name: 'Bruma root', xp: 3.8 },
      { name: 'Ent trunk', xp: 25, notes: 'Varies by tree type' }
    ]
  },
  {
    skill: 'Fletching',
    actions: [
      { name: 'Arrow shafts', xp: 5 },
      { name: 'Headless arrows', xp: 1 },
      { name: 'Ogre arrow shafts', xp: 1.6, level: 5, category: 'Arrows' },
      { name: 'Flighted ogre arrows', xp: 0.9, level: 5, category: 'Arrows' },
      { name: 'Bronze arrows', xp: 1.3 },
      { name: 'Iron arrows', xp: 2.5 },
      { name: 'Steel arrows', xp: 5 },
      { name: 'Mithril arrows', xp: 7.5 },
      { name: 'Adamant arrows', xp: 10 },
      { name: 'Rune arrows', xp: 12.5 },
      { name: 'Amethyst arrows', xp: 13.5 },
      { name: 'Bronze javelins', xp: 1, level: 3, category: 'Javelins' },
      { name: 'Iron javelins', xp: 2, level: 17, category: 'Javelins' },
      { name: 'Steel javelins', xp: 5, level: 32, category: 'Javelins' },
      { name: 'Mithril javelins', xp: 8, level: 47, category: 'Javelins' },
      { name: 'Adamant javelins', xp: 10, level: 62, category: 'Javelins' },
      { name: 'Rune javelins', xp: 12.4, level: 77, category: 'Javelins' },
      { name: 'Amethyst javelins', xp: 13.5, level: 84, category: 'Javelins' },
      { name: 'Dragon javelins', xp: 25, level: 92, category: 'Javelins' },
      { name: 'Bronze darts', xp: 1.8 },
      { name: 'Iron darts', xp: 3.8 },
      { name: 'Steel darts', xp: 7.5 },
      { name: 'Mithril darts', xp: 11.2 },
      { name: 'Adamant darts', xp: 15 },
      { name: 'Rune darts', xp: 18.8 },
      { name: 'Amethyst darts', xp: 21, level: 90, category: 'Darts' },
      { name: 'Dragon darts', xp: 25 },
      { name: 'Shortbow', xp: 5 },
      { name: 'Longbow', xp: 10 },
      { name: 'Oak shortbow', xp: 16.5 },
      { name: 'Oak longbow', xp: 25 },
      { name: 'Willow shortbow', xp: 33.3 },
      { name: 'Willow longbow', xp: 41.5 },
      { name: 'Maple shortbow', xp: 50 },
      { name: 'Maple longbow', xp: 58.3 },
      { name: 'Yew shortbow', xp: 67.5 },
      { name: 'Yew longbow', xp: 75 },
      { name: 'Magic shortbow', xp: 83.3 },
      { name: 'Magic longbow', xp: 91.5 },
      { name: 'Redwood shield', xp: 216 },
      { name: 'Wooden stock', xp: 6, level: 9, category: 'Crossbows' },
      { name: 'Oak stock', xp: 16, level: 24, category: 'Crossbows' },
      { name: 'Willow stock', xp: 22, level: 39, category: 'Crossbows' },
      { name: 'Teak stock', xp: 27, level: 46, category: 'Crossbows' },
      { name: 'Maple stock', xp: 32, level: 54, category: 'Crossbows' },
      { name: 'Mahogany stock', xp: 41, level: 61, category: 'Crossbows' },
      { name: 'Yew stock', xp: 50, level: 69, category: 'Crossbows' },
      { name: 'Bronze crossbow', xp: 6, level: 9, category: 'Crossbows' },
      { name: 'Iron crossbow', xp: 22, level: 39, category: 'Crossbows' },
      { name: 'Steel crossbow', xp: 27, level: 46, category: 'Crossbows' },
      { name: 'Mithril crossbow', xp: 32, level: 54, category: 'Crossbows' },
      { name: 'Adamant crossbow', xp: 41, level: 61, category: 'Crossbows' },
      { name: 'Rune crossbow', xp: 50, level: 69, category: 'Crossbows' },
      { name: 'Broad arrows', xp: 15 },
      { name: 'Broad bolts', xp: 3 },
      { name: 'Opal bolts', xp: 1.6, level: 11, category: 'Bolts' },
      { name: 'Jade bolts', xp: 2.4, level: 26, category: 'Bolts' },
      { name: 'Pearl bolts', xp: 3.2, level: 41, category: 'Bolts' },
      { name: 'Topaz bolts', xp: 3.9, level: 48, category: 'Bolts' },
      { name: 'Sapphire bolts', xp: 4, level: 56, category: 'Bolts' },
      { name: 'Emerald bolts', xp: 5.5, level: 58, category: 'Bolts' },
      { name: 'Ruby bolts', xp: 6.3 },
      { name: 'Diamond bolts', xp: 7 },
      { name: 'Dragonstone bolts', xp: 8.2, level: 71, category: 'Bolts' },
      { name: 'Onyx bolts', xp: 9.4, level: 73, category: 'Bolts' },
      { name: 'Dragon bolts', xp: 12 },
      { name: 'Ruby dragon bolts', xp: 6.3 }
    ]
  },
  {
    skill: 'Fishing',
    actions: [
      { name: 'Shrimp', xp: 10 },
      { name: 'Sardine', xp: 20 },
      { name: 'Herring', xp: 30 },
      { name: 'Anchovies', xp: 40 },
      { name: 'Mackerel', xp: 20, level: 16, category: 'Fish' },
      { name: 'Trout', xp: 50 },
      { name: 'Salmon', xp: 70 },
      { name: 'Pike', xp: 60 },
      { name: 'Lobster', xp: 90 },
      { name: 'Tuna', xp: 80 },
      { name: 'Swordfish', xp: 100 },
      { name: 'Karambwan', xp: 50 },
      { name: 'Bass', xp: 100, level: 46, category: 'Fish' },
      { name: 'Cave eel', xp: 80, level: 38, category: 'Fish' },
      { name: 'Lava eel', xp: 60, level: 53, category: 'Fish' },
      { name: 'Monkfish', xp: 120 },
      { name: 'Shark', xp: 110 },
      { name: 'Anglerfish', xp: 120 },
      { name: 'Leaping trout', xp: 50 },
      { name: 'Leaping salmon', xp: 70 },
      { name: 'Leaping sturgeon', xp: 80 },
      { name: 'Sacred eel', xp: 105 },
      { name: 'Infernal eel', xp: 95 },
      { name: 'Dark crab', xp: 130 },
      { name: 'Minnow', xp: 26.1 },
      { name: 'Karambwanji', xp: 5 },
      { name: 'Bluegill', xp: 11.5, level: 43, category: 'Aerial fishing' },
      { name: 'Common tench', xp: 40, level: 56, category: 'Aerial fishing' },
      { name: 'Mottled eel', xp: 65, level: 73, category: 'Aerial fishing' },
      { name: 'Greater siren', xp: 87, level: 91, category: 'Aerial fishing' },
      { name: 'Drift net catch', xp: 720, level: 47, category: 'Drift net' },
      { name: 'Tempoross permit', xp: 1, level: 35, category: 'Tempoross', notes: 'Use reward screen XP for exact calc' }
    ]
  },
  {
    skill: 'Firemaking',
    actions: [
      { name: 'Logs', xp: 40 },
      { name: 'Achey logs', xp: 40 },
      { name: 'Oak logs', xp: 60 },
      { name: 'Willow logs', xp: 90 },
      { name: 'Teak logs', xp: 105 },
      { name: 'Arctic pine logs', xp: 125 },
      { name: 'Maple logs', xp: 135 },
      { name: 'Mahogany logs', xp: 157.5 },
      { name: 'Yew logs', xp: 202.5 },
      { name: 'Magic logs', xp: 303.8 },
      { name: 'Redwood logs', xp: 350 },
      { name: 'Pyre logs', xp: 50 },
      { name: 'Oak pyre logs', xp: 70 },
      { name: 'Willow pyre logs', xp: 100 },
      { name: 'Maple pyre logs', xp: 175 },
      { name: 'Yew pyre logs', xp: 255 },
      { name: 'Magic pyre logs', xp: 404.5 },
      { name: 'Redwood pyre logs', xp: 500 },
      { name: 'Wintertodt point', xp: 1, notes: 'Use reward screen XP for exact calc' },
      { name: 'Shades pyre log', xp: 175 }
    ]
  },
  {
    skill: 'Crafting',
    actions: [
      { name: 'Pot', xp: 6.3, level: 1, category: 'Pottery' },
      { name: 'Pie dish', xp: 15, level: 7, category: 'Pottery' },
      { name: 'Bowl', xp: 33, level: 8, category: 'Pottery' },
      { name: 'Plant pot', xp: 37.5, level: 19, category: 'Pottery' },
      { name: 'Pot lid', xp: 40, level: 25, category: 'Pottery' },
      { name: 'Beer glass', xp: 17.5, level: 1, category: 'Glassblowing' },
      { name: 'Candle lantern', xp: 19, level: 4, category: 'Glassblowing' },
      { name: 'Oil lamp', xp: 25, level: 12, category: 'Glassblowing' },
      { name: 'Vial', xp: 35, level: 33, category: 'Glassblowing' },
      { name: 'Fishbowl', xp: 42.5, level: 42, category: 'Glassblowing' },
      { name: 'Unpowered orb', xp: 52.5, level: 46, category: 'Glassblowing' },
      { name: 'Lantern lens', xp: 55, level: 49, category: 'Glassblowing' },
      { name: 'Light orb', xp: 70, level: 87, category: 'Glassblowing' },
      { name: 'Cut opal', xp: 15, level: 1, category: 'Gems' },
      { name: 'Cut jade', xp: 20, level: 13, category: 'Gems' },
      { name: 'Cut red topaz', xp: 25, level: 16, category: 'Gems' },
      { name: 'Cut sapphire', xp: 50, level: 20, category: 'Gems' },
      { name: 'Cut emerald', xp: 67.5, level: 27, category: 'Gems' },
      { name: 'Cut ruby', xp: 85, level: 34, category: 'Gems' },
      { name: 'Cut diamond', xp: 107.5, level: 43, category: 'Gems' },
      { name: 'Cut dragonstone', xp: 137.5, level: 55, category: 'Gems' },
      { name: 'Cut onyx', xp: 167.5, level: 67, category: 'Gems' },
      { name: 'Cut zenyte', xp: 200, level: 89, category: 'Gems' },
      { name: 'Leather gloves', xp: 13.8 },
      { name: 'Leather boots', xp: 16.3 },
      { name: 'Leather cowl', xp: 18.5 },
      { name: 'Leather vambraces', xp: 22 },
      { name: 'Leather body', xp: 25 },
      { name: 'Hardleather body', xp: 35 },
      { name: 'Coif', xp: 37 },
      { name: 'Air battlestaff', xp: 137.5 },
      { name: 'Water battlestaff', xp: 100 },
      { name: 'Earth battlestaff', xp: 112.5 },
      { name: 'Fire battlestaff', xp: 125 },
      { name: 'Gold bracelet', xp: 25 },
      { name: 'Gold ring', xp: 15 },
      { name: 'Gold necklace', xp: 20 },
      { name: 'Gold amulet', xp: 30 },
      { name: 'Sapphire ring', xp: 40 },
      { name: 'Sapphire necklace', xp: 55 },
      { name: 'Sapphire bracelet', xp: 60 },
      { name: 'Sapphire amulet', xp: 65 },
      { name: 'Emerald ring', xp: 55 },
      { name: 'Emerald necklace', xp: 60 },
      { name: 'Emerald bracelet', xp: 65 },
      { name: 'Emerald amulet', xp: 70 },
      { name: 'Ruby ring', xp: 70 },
      { name: 'Ruby necklace', xp: 75 },
      { name: 'Ruby bracelet', xp: 80 },
      { name: 'Ruby amulet', xp: 85 },
      { name: 'Diamond ring', xp: 85 },
      { name: 'Diamond necklace', xp: 90 },
      { name: 'Diamond bracelet', xp: 95 },
      { name: 'Diamond amulet', xp: 100 },
      { name: 'Dragonstone ring', xp: 100 },
      { name: 'Dragonstone necklace', xp: 105 },
      { name: 'Dragonstone bracelet', xp: 110 },
      { name: 'Dragonstone amulet', xp: 150 },
      { name: 'Green d\'hide vambraces', xp: 62 },
      { name: 'Green d\'hide chaps', xp: 124 },
      { name: 'Green d\'hide body', xp: 186 },
      { name: 'Blue d\'hide vambraces', xp: 70 },
      { name: 'Blue d\'hide chaps', xp: 140 },
      { name: 'Blue d\'hide body', xp: 210 },
      { name: 'Red d\'hide vambraces', xp: 78 },
      { name: 'Red d\'hide chaps', xp: 156 },
      { name: 'Red d\'hide body', xp: 234 },
      { name: 'Black d\'hide vambraces', xp: 86 },
      { name: 'Black d\'hide chaps', xp: 172 },
      { name: 'Black d\'hide body', xp: 258 },
      { name: 'Battlestaff', xp: 125 }
    ]
  },
  {
    skill: 'Smithing',
    actions: [
      { name: 'Bronze bar', xp: 6.2 },
      { name: 'Iron bar', xp: 12.5 },
      { name: 'Steel bar', xp: 17.5 },
      { name: 'Silver bar', xp: 13.7 },
      { name: 'Gold bar', xp: 22.5 },
      { name: 'Mithril bar', xp: 30 },
      { name: 'Adamantite bar', xp: 37.5 },
      { name: 'Runite bar', xp: 50 },
      { name: 'Cannonball set', xp: 25.6 },
      { name: 'Gold bar with gauntlets', xp: 56.2 },
      { name: 'Bronze platebody', xp: 62.5 },
      { name: 'Iron platebody', xp: 125 },
      { name: 'Steel platebody', xp: 187.5 },
      { name: 'Mithril platebody', xp: 250 },
      { name: 'Adamant platebody', xp: 312.5 },
      { name: 'Rune platebody', xp: 375 },
      { name: 'Bronze platelegs', xp: 37.5, level: 16, category: 'Armour' },
      { name: 'Iron platelegs', xp: 75, level: 31, category: 'Armour' },
      { name: 'Steel platelegs', xp: 112.5, level: 46, category: 'Armour' },
      { name: 'Mithril platelegs', xp: 150, level: 66, category: 'Armour' },
      { name: 'Adamant platelegs', xp: 187.5, level: 86, category: 'Armour' },
      { name: 'Rune platelegs', xp: 225, level: 99, category: 'Armour' },
      { name: 'Bronze full helm', xp: 25, level: 7, category: 'Armour' },
      { name: 'Iron full helm', xp: 50, level: 22, category: 'Armour' },
      { name: 'Steel full helm', xp: 75, level: 37, category: 'Armour' },
      { name: 'Mithril full helm', xp: 100, level: 57, category: 'Armour' },
      { name: 'Adamant full helm', xp: 125, level: 77, category: 'Armour' },
      { name: 'Rune full helm', xp: 150, level: 92, category: 'Armour' },
      { name: 'Bronze scimitar', xp: 25, level: 5, category: 'Weapons' },
      { name: 'Iron scimitar', xp: 50, level: 20, category: 'Weapons' },
      { name: 'Steel scimitar', xp: 75, level: 35, category: 'Weapons' },
      { name: 'Mithril scimitar', xp: 100, level: 55, category: 'Weapons' },
      { name: 'Adamant scimitar', xp: 125, level: 75, category: 'Weapons' },
      { name: 'Rune scimitar', xp: 150, level: 90, category: 'Weapons' },
      { name: 'Bronze 2h sword', xp: 37.5, level: 14, category: 'Weapons' },
      { name: 'Iron 2h sword', xp: 75, level: 29, category: 'Weapons' },
      { name: 'Steel 2h sword', xp: 112.5, level: 44, category: 'Weapons' },
      { name: 'Mithril 2h sword', xp: 150, level: 64, category: 'Weapons' },
      { name: 'Adamant 2h sword', xp: 187.5, level: 84, category: 'Weapons' },
      { name: 'Rune 2h sword', xp: 225, level: 99, category: 'Weapons' },
      { name: 'Bronze dart tips', xp: 12.5 },
      { name: 'Iron dart tips', xp: 25 },
      { name: 'Steel dart tips', xp: 37.5 },
      { name: 'Mithril dart tips', xp: 50 },
      { name: 'Adamant dart tips', xp: 62.5 },
      { name: 'Rune dart tips', xp: 75 },
      { name: 'Giant\'s Foundry sword', xp: 12_000, notes: 'Approx. per hand-in' }
    ]
  },
  {
    skill: 'Mining',
    actions: [
      { name: 'Copper or tin ore', xp: 17.5 },
      { name: 'Clay', xp: 5 },
      { name: 'Rune essence', xp: 5 },
      { name: 'Pure essence', xp: 5, level: 30, category: 'Essence' },
      { name: 'Blurite ore', xp: 17.5 },
      { name: 'Iron ore', xp: 35 },
      { name: 'Silver ore', xp: 40 },
      { name: 'Coal', xp: 50 },
      { name: 'Gold ore', xp: 65 },
      { name: 'Volcanic ash', xp: 10, level: 22, category: 'Minerals' },
      { name: 'Basalt', xp: 5, level: 72, category: 'Minerals' },
      { name: 'Daeyalt essence', xp: 5, level: 60, category: 'Essence' },
      { name: 'Dense essence block', xp: 12, level: 38, category: 'Essence' },
      { name: 'Gem rock', xp: 65 },
      { name: 'Granite 500g', xp: 50 },
      { name: 'Granite 2kg', xp: 60 },
      { name: 'Granite 5kg', xp: 75 },
      { name: 'Sandstone 1kg', xp: 30 },
      { name: 'Sandstone 2kg', xp: 40 },
      { name: 'Sandstone 5kg', xp: 50 },
      { name: 'Sandstone 10kg', xp: 60 },
      { name: 'Mithril ore', xp: 80 },
      { name: 'Adamantite ore', xp: 95 },
      { name: 'Runite ore', xp: 125 },
      { name: 'Lovakite ore', xp: 10 },
      { name: 'Amethyst', xp: 240 },
      { name: 'Calcified deposit', xp: 20, level: 41, category: 'Minerals' },
      { name: 'Motherlode pay-dirt', xp: 60 },
      { name: 'Volcanic Mine point', xp: 1, notes: 'Use final XP for exact calc' }
    ]
  },
  {
    skill: 'Herblore',
    actions: [
      { name: 'Clean guam leaf', xp: 2.5, level: 3, category: 'Cleaning herbs' },
      { name: 'Clean marrentill', xp: 3.8, level: 5, category: 'Cleaning herbs' },
      { name: 'Clean tarromin', xp: 5, level: 11, category: 'Cleaning herbs' },
      { name: 'Clean harralander', xp: 6.3, level: 20, category: 'Cleaning herbs' },
      { name: 'Clean ranarr weed', xp: 7.5, level: 25, category: 'Cleaning herbs' },
      { name: 'Clean toadflax', xp: 8, level: 30, category: 'Cleaning herbs' },
      { name: 'Clean irit leaf', xp: 8.8, level: 40, category: 'Cleaning herbs' },
      { name: 'Clean avantoe', xp: 10, level: 48, category: 'Cleaning herbs' },
      { name: 'Clean kwuarm', xp: 11.3, level: 54, category: 'Cleaning herbs' },
      { name: 'Clean snapdragon', xp: 11.8, level: 59, category: 'Cleaning herbs' },
      { name: 'Clean cadantine', xp: 12.5, level: 65, category: 'Cleaning herbs' },
      { name: 'Clean lantadyme', xp: 13.1, level: 67, category: 'Cleaning herbs' },
      { name: 'Clean dwarf weed', xp: 13.8, level: 70, category: 'Cleaning herbs' },
      { name: 'Clean torstol', xp: 15, level: 75, category: 'Cleaning herbs' },
      { name: 'Guam tar', xp: 30 },
      { name: 'Marrentill tar', xp: 42.5 },
      { name: 'Tarromin tar', xp: 55 },
      { name: 'Harralander tar', xp: 72.5 },
      { name: 'Attack potion', xp: 25 },
      { name: 'Antipoison', xp: 37.5 },
      { name: 'Relicym\'s balm', xp: 40 },
      { name: 'Strength potion', xp: 50 },
      { name: 'Serum 207', xp: 50 },
      { name: 'Compost potion', xp: 60 },
      { name: 'Restore potion', xp: 62.5 },
      { name: 'Energy potion', xp: 67.5 },
      { name: 'Defence potion', xp: 75 },
      { name: 'Agility potion', xp: 80 },
      { name: 'Prayer potion', xp: 87.5 },
      { name: 'Super energy', xp: 117.5 },
      { name: 'Super attack', xp: 100 },
      { name: 'Superantipoison', xp: 106.3 },
      { name: 'Fishing potion', xp: 112.5 },
      { name: 'Super strength', xp: 125 },
      { name: 'Weapon poison', xp: 137.5 },
      { name: 'Super restore', xp: 142.5 },
      { name: 'Super defence', xp: 150 },
      { name: 'Antifire potion', xp: 157.5 },
      { name: 'Ranging potion', xp: 162.5 },
      { name: 'Magic potion', xp: 172.5 },
      { name: 'Saradomin brew', xp: 180 },
      { name: 'Super combat potion', xp: 150 },
      { name: 'Stamina potion', xp: 102 },
      { name: 'Zamorak brew', xp: 175 },
      { name: 'Antidote+', xp: 155 },
      { name: 'Antidote++', xp: 177.5 },
      { name: 'Anti-venom', xp: 120 },
      { name: 'Anti-venom+', xp: 125 },
      { name: 'Extended antifire', xp: 110 },
      { name: 'Divine ranging potion', xp: 2 },
      { name: 'Divine super combat potion', xp: 2 }
    ]
  },
  {
    skill: 'Agility',
    actions: [
      { name: 'Gnome Stronghold lap', xp: 86.5 },
      { name: 'Shayzien basic lap', xp: 133 },
      { name: 'Draynor Village lap', xp: 120 },
      { name: 'Al Kharid lap', xp: 180 },
      { name: 'Penguin agility lap', xp: 540 },
      { name: 'Barbarian Outpost lap', xp: 153.2 },
      { name: 'Ape Atoll lap', xp: 580 },
      { name: 'Canifis lap', xp: 240 },
      { name: 'Falador lap', xp: 440 },
      { name: 'Seers\' Village lap', xp: 570 },
      { name: 'Pollnivneach lap', xp: 890 },
      { name: 'Rellekka lap', xp: 780 },
      { name: 'Ardougne lap', xp: 793 },
      { name: 'Prifddinas lap', xp: 1_337 },
      { name: 'Wilderness lap', xp: 571.4 },
      { name: 'Dorgesh-Kaan lap', xp: 2_750 },
      { name: 'Werewolf course lap', xp: 730 },
      { name: 'Hallowed Sepulchre floor 1', xp: 575 },
      { name: 'Hallowed Sepulchre floor 2', xp: 1_800 },
      { name: 'Hallowed Sepulchre floor 3', xp: 3_000 },
      { name: 'Hallowed Sepulchre floor 4', xp: 4_800 },
      { name: 'Hallowed Sepulchre floor 5', xp: 5_700 }
    ]
  },
  {
    skill: 'Thieving',
    actions: [
      { name: 'Man/Woman pickpocket', xp: 8 },
      { name: 'Tea stall', xp: 16 },
      { name: 'Silk stall', xp: 24 },
      { name: 'Cake stall', xp: 16 },
      { name: 'Fruit stall', xp: 28.5 },
      { name: 'Vegetable stall', xp: 10, level: 2, category: 'Stalls' },
      { name: 'Crafting stall', xp: 10, level: 5, category: 'Stalls' },
      { name: 'Monkey food stall', xp: 16, level: 5, category: 'Stalls' },
      { name: 'General stall', xp: 16, level: 5, category: 'Stalls' },
      { name: 'Seed stall', xp: 10, level: 27, category: 'Stalls' },
      { name: 'Fur stall', xp: 36, level: 35, category: 'Stalls' },
      { name: 'Fish stall', xp: 42, level: 42, category: 'Stalls' },
      { name: 'Silver stall', xp: 54, level: 50, category: 'Stalls' },
      { name: 'Spice stall', xp: 81.3, level: 65, category: 'Stalls' },
      { name: 'Gem stall', xp: 160, level: 75, category: 'Stalls' },
      { name: 'Wall safe', xp: 70, level: 50, category: 'Safes' },
      { name: 'Master farmer pickpocket', xp: 43 },
      { name: 'Guard pickpocket', xp: 46.8 },
      { name: 'Warrior woman pickpocket', xp: 26 },
      { name: 'Rogue pickpocket', xp: 36.5 },
      { name: 'Cave goblin pickpocket', xp: 40 },
      { name: 'Fremennik citizen pickpocket', xp: 65 },
      { name: 'Bearded Pollnivnian bandit', xp: 65 },
      { name: 'Menaphite thug', xp: 137.5 },
      { name: 'Paladin pickpocket', xp: 151.8 },
      { name: 'Knight of Ardougne pickpocket', xp: 84.3 },
      { name: 'Gnome pickpocket', xp: 198.3 },
      { name: 'Hero pickpocket', xp: 273.3 },
      { name: 'Elf pickpocket', xp: 353.3 },
      { name: 'Pyramid Plunder room', xp: 1_000, notes: 'Approx. per room' },
      { name: 'Vyrewatch Sentinel pickpocket', xp: 306.9 },
      { name: 'Elven worker pickpocket', xp: 353.3 },
      { name: 'Blackjacking action', xp: 65 }
    ]
  },
  {
    skill: 'Slayer',
    actions: [
      { name: 'Low-level task monster', xp: 50 },
      { name: 'Mid-level task monster', xp: 100 },
      { name: 'High-level task monster', xp: 150 },
      { name: 'Crawling Hand', xp: 15, level: 5, category: 'Slayer monsters' },
      { name: 'Cave crawler', xp: 22, level: 10, category: 'Slayer monsters' },
      { name: 'Banshee', xp: 22, level: 15, category: 'Slayer monsters' },
      { name: 'Rockslug', xp: 27, level: 20, category: 'Slayer monsters' },
      { name: 'Cockatrice', xp: 37, level: 25, category: 'Slayer monsters' },
      { name: 'Pyrefiend', xp: 45, level: 30, category: 'Slayer monsters' },
      { name: 'Mogre', xp: 48, level: 32, category: 'Slayer monsters' },
      { name: 'Harpie Bug Swarm', xp: 25, level: 33, category: 'Slayer monsters' },
      { name: 'Wall beast', xp: 105, level: 35, category: 'Slayer monsters' },
      { name: 'Killerwatt', xp: 51, level: 37, category: 'Slayer monsters' },
      { name: 'Basilisk', xp: 75, level: 40, category: 'Slayer monsters' },
      { name: 'Fever spider', xp: 40, level: 42, category: 'Slayer monsters' },
      { name: 'Infernal mage', xp: 60, level: 45, category: 'Slayer monsters' },
      { name: 'Dust devil', xp: 105 },
      { name: 'Jelly', xp: 75, level: 52, category: 'Slayer monsters' },
      { name: 'Turoth', xp: 77, level: 55, category: 'Slayer monsters' },
      { name: 'Warped terrorbird', xp: 143, level: 56, category: 'Slayer monsters' },
      { name: 'Cave horror', xp: 55, level: 58, category: 'Slayer monsters' },
      { name: 'Aberrant spectre', xp: 90, level: 60, category: 'Slayer monsters' },
      { name: 'Spiritual ranger', xp: 106, level: 63, category: 'Slayer monsters' },
      { name: 'Spiritual warrior', xp: 110, level: 68, category: 'Slayer monsters' },
      { name: 'Nechryael', xp: 105 },
      { name: 'Abyssal demon', xp: 150 },
      { name: 'Gargoyle', xp: 105 },
      { name: 'Kurask', xp: 97 },
      { name: 'Bloodveld', xp: 120 },
      { name: 'Skeletal wyvern', xp: 210, level: 72, category: 'Slayer monsters' },
      { name: 'Brutal black dragon', xp: 250, level: 77, category: 'Slayer monsters' },
      { name: 'Spiritual mage', xp: 85, level: 83, category: 'Slayer monsters' },
      { name: 'Abyssal Sire', xp: 400, level: 85, category: 'Slayer bosses' },
      { name: 'Kraken', xp: 255, level: 87, category: 'Slayer bosses' },
      { name: 'Cave kraken', xp: 125, level: 87, category: 'Slayer monsters' },
      { name: 'Dark beast', xp: 220, level: 90, category: 'Slayer monsters' },
      { name: 'Thermonuclear smoke devil', xp: 240, level: 93, category: 'Slayer bosses' },
      { name: 'Smoke devil', xp: 185, level: 93, category: 'Slayer monsters' },
      { name: 'Hydra', xp: 309 },
      { name: 'Alchemical Hydra', xp: 1_320, level: 95, category: 'Slayer bosses' }
    ]
  },
  {
    skill: 'Farming',
    actions: [
      { name: 'Barley harvest', xp: 9.5, level: 3, category: 'Hops' },
      { name: 'Hammerstone hops harvest', xp: 10.5, level: 4, category: 'Hops' },
      { name: 'Asgarnian hops harvest', xp: 19, level: 8, category: 'Hops' },
      { name: 'Jute harvest', xp: 23, level: 13, category: 'Hops' },
      { name: 'Yanillian hops harvest', xp: 35.5, level: 16, category: 'Hops' },
      { name: 'Krandorian hops harvest', xp: 50.5, level: 21, category: 'Hops' },
      { name: 'Wildblood hops harvest', xp: 58.5, level: 28, category: 'Hops' },
      { name: 'Marigold harvest', xp: 47 },
      { name: 'Rosemary harvest', xp: 66.5 },
      { name: 'Nasturtium harvest', xp: 111 },
      { name: 'Limpwurt root harvest', xp: 120 },
      { name: 'Potato harvest', xp: 8 },
      { name: 'Onion harvest', xp: 9.5 },
      { name: 'Cabbage harvest', xp: 11.5 },
      { name: 'Strawberry harvest', xp: 29 },
      { name: 'Sweetcorn harvest', xp: 34 },
      { name: 'Watermelon harvest', xp: 48.5 },
      { name: 'Guam herb harvest', xp: 12.5 },
      { name: 'Marrentill herb harvest', xp: 15 },
      { name: 'Tarromin herb harvest', xp: 18 },
      { name: 'Ranarr herb harvest', xp: 30.5 },
      { name: 'Toadflax herb harvest', xp: 38.5 },
      { name: 'Irit herb harvest', xp: 48.5 },
      { name: 'Avantoe herb harvest', xp: 61.5 },
      { name: 'Kwuarm herb harvest', xp: 78 },
      { name: 'Snapdragon herb harvest', xp: 98.5 },
      { name: 'Cadantine herb harvest', xp: 120 },
      { name: 'Lantadyme herb harvest', xp: 151.5 },
      { name: 'Dwarf weed herb harvest', xp: 192 },
      { name: 'Torstol herb harvest', xp: 224.5 },
      { name: 'Redberry bush check-health', xp: 64, level: 10, category: 'Bushes' },
      { name: 'Cadavaberry bush check-health', xp: 102.5, level: 22, category: 'Bushes' },
      { name: 'Dwellberry bush check-health', xp: 177.5, level: 36, category: 'Bushes' },
      { name: 'Jangerberry bush check-health', xp: 284.5, level: 48, category: 'Bushes' },
      { name: 'Whiteberry bush check-health', xp: 437.5, level: 59, category: 'Bushes' },
      { name: 'Poison ivy bush check-health', xp: 674, level: 70, category: 'Bushes' },
      { name: 'Oak tree check-health', xp: 467.5 },
      { name: 'Willow tree check-health', xp: 1_456.5 },
      { name: 'Maple tree check-health', xp: 3_403.4 },
      { name: 'Yew tree check-health', xp: 7_069.9 },
      { name: 'Magic tree check-health', xp: 13_768.3 },
      { name: 'Redwood tree check-health', xp: 22_450 },
      { name: 'Teak tree check-health', xp: 7_290, level: 35, category: 'Hardwood trees' },
      { name: 'Mahogany tree check-health', xp: 15_720, level: 55, category: 'Hardwood trees' },
      { name: 'Apple tree check-health', xp: 1_199.5 },
      { name: 'Banana tree check-health', xp: 1_750.5 },
      { name: 'Orange tree check-health', xp: 2_470.2 },
      { name: 'Curry tree check-health', xp: 2_906.9 },
      { name: 'Papaya tree check-health', xp: 6_146.4 },
      { name: 'Palm tree check-health', xp: 10_150.1 },
      { name: 'Calquat tree check-health', xp: 12_096 },
      { name: 'Dragonfruit tree check-health', xp: 17_335 },
      { name: 'Cactus check-health', xp: 374, level: 55, category: 'Special patches' },
      { name: 'Potato cactus harvest', xp: 68, level: 64, category: 'Special patches' },
      { name: 'Giant seaweed harvest', xp: 21, level: 23, category: 'Special patches' },
      { name: 'Mushroom harvest', xp: 57.7, level: 53, category: 'Special patches' },
      { name: 'Belladonna harvest', xp: 512, level: 63, category: 'Special patches' },
      { name: 'Celastrus tree check-health', xp: 14_130, level: 85, category: 'Special patches' },
      { name: 'Crystal tree check-health', xp: 15_000, level: 74, category: 'Special patches' },
      { name: 'Hespori harvest', xp: 12_600, level: 65, category: 'Special patches' }
    ]
  },
  {
    skill: 'Runecraft',
    actions: [
      { name: 'Air tiara', xp: 25, level: 1, category: 'Tiaras' },
      { name: 'Mind tiara', xp: 27.5, level: 2, category: 'Tiaras' },
      { name: 'Water tiara', xp: 30, level: 5, category: 'Tiaras' },
      { name: 'Earth tiara', xp: 32.5, level: 9, category: 'Tiaras' },
      { name: 'Fire tiara', xp: 35, level: 14, category: 'Tiaras' },
      { name: 'Body tiara', xp: 37.5, level: 20, category: 'Tiaras' },
      { name: 'Cosmic tiara', xp: 40, level: 27, category: 'Tiaras' },
      { name: 'Chaos tiara', xp: 42.5, level: 35, category: 'Tiaras' },
      { name: 'Nature tiara', xp: 45, level: 44, category: 'Tiaras' },
      { name: 'Law tiara', xp: 47.5, level: 54, category: 'Tiaras' },
      { name: 'Death tiara', xp: 50, level: 65, category: 'Tiaras' },
      { name: 'Air rune essence', xp: 5 },
      { name: 'Mind rune essence', xp: 5.5 },
      { name: 'Water rune essence', xp: 6 },
      { name: 'Earth rune essence', xp: 6.5 },
      { name: 'Fire rune essence', xp: 7 },
      { name: 'Body rune essence', xp: 7.5 },
      { name: 'Cosmic rune essence', xp: 8 },
      { name: 'Chaos rune essence', xp: 8.5 },
      { name: 'Astral rune essence', xp: 8.7 },
      { name: 'Nature rune essence', xp: 9 },
      { name: 'Law rune essence', xp: 9.5 },
      { name: 'Death rune essence', xp: 10 },
      { name: 'Wrath rune essence', xp: 8 },
      { name: 'Blood rune essence', xp: 23.8 },
      { name: 'Soul rune essence', xp: 29.7 },
      { name: 'Lava rune essence', xp: 10.5 },
      { name: 'Steam rune essence', xp: 9.5 },
      { name: 'Smoke rune essence', xp: 9.5 },
      { name: 'Mist rune essence', xp: 8 },
      { name: 'Dust rune essence', xp: 8.3 },
      { name: 'Mud rune essence', xp: 9.3 },
      { name: 'Guardians of the Rift point', xp: 1, notes: 'Use reward XP for exact calc' }
    ]
  },
  {
    skill: 'Hunter',
    actions: [
      { name: 'Bird house run - regular', xp: 280, level: 5, category: 'Bird houses' },
      { name: 'Bird house run - oak', xp: 420, level: 14, category: 'Bird houses' },
      { name: 'Bird house run - willow', xp: 560, level: 24, category: 'Bird houses' },
      { name: 'Bird house run - teak', xp: 700, level: 34, category: 'Bird houses' },
      { name: 'Bird house run - maple', xp: 820, level: 44, category: 'Bird houses' },
      { name: 'Bird house run - mahogany', xp: 960, level: 49, category: 'Bird houses' },
      { name: 'Bird house run - yew', xp: 1_020, level: 59, category: 'Bird houses' },
      { name: 'Bird house run - magic', xp: 1_140, level: 74, category: 'Bird houses' },
      { name: 'Bird house run - redwood', xp: 1_200, level: 89, category: 'Bird houses' },
      { name: 'Polar kebbit', xp: 30 },
      { name: 'Crimson swift', xp: 34 },
      { name: 'Common kebbit', xp: 36 },
      { name: 'Golden warbler', xp: 47 },
      { name: 'Feldip weasel', xp: 48 },
      { name: 'Copper longtail', xp: 61 },
      { name: 'Cerulean twitch', xp: 64.5 },
      { name: 'Desert devil', xp: 66 },
      { name: 'Ruby harvest', xp: 24 },
      { name: 'Sapphire glacialis', xp: 34, level: 25, category: 'Butterflies' },
      { name: 'Snowy knight', xp: 44, level: 35, category: 'Butterflies' },
      { name: 'Black warlock', xp: 54, level: 45, category: 'Butterflies' },
      { name: 'Tropical wagtail', xp: 95 },
      { name: 'Wild kebbit', xp: 128 },
      { name: 'Swamp lizard', xp: 152 },
      { name: 'Orange salamander', xp: 224 },
      { name: 'Chinchompa', xp: 198.4 },
      { name: 'Falconry spotted kebbit', xp: 104 },
      { name: 'Falconry dark kebbit', xp: 132 },
      { name: 'Falconry dashing kebbit', xp: 156 },
      { name: 'Red salamander', xp: 272 },
      { name: 'Red chinchompa', xp: 265 },
      { name: 'Black chinchompa', xp: 315 },
      { name: 'Black salamander', xp: 319.5 },
      { name: 'Carnivorous chinchompa', xp: 265 },
      { name: 'Dragon impling', xp: 553 },
      { name: 'Baby impling', xp: 18, level: 17, category: 'Implings' },
      { name: 'Young impling', xp: 20, level: 22, category: 'Implings' },
      { name: 'Gourmet impling', xp: 22, level: 28, category: 'Implings' },
      { name: 'Earth impling', xp: 25, level: 36, category: 'Implings' },
      { name: 'Essence impling', xp: 27, level: 42, category: 'Implings' },
      { name: 'Eclectic impling', xp: 30, level: 50, category: 'Implings' },
      { name: 'Nature impling', xp: 34, level: 58, category: 'Implings' },
      { name: 'Magpie impling', xp: 44, level: 65, category: 'Implings' },
      { name: 'Ninja impling', xp: 52, level: 74, category: 'Implings' },
      { name: 'Herbiboar harvest', xp: 1_950 },
      { name: 'Bird house run', xp: 4_000, notes: 'Approx. per full run' },
      { name: 'Maniacal monkey', xp: 1_000 },
      { name: 'Sunlight antelope', xp: 1_200 }
    ]
  },
  {
    skill: 'Construction',
    actions: [
      { name: 'Crude wooden chair', xp: 58 },
      { name: 'Wooden chair', xp: 87 },
      { name: 'Wooden bookcase', xp: 115 },
      { name: 'Wooden shelves 1', xp: 87, level: 6, category: 'Furniture' },
      { name: 'Beer barrel', xp: 87, level: 7, category: 'Furniture' },
      { name: 'Wood dining table', xp: 115, level: 10, category: 'Furniture' },
      { name: 'Rocking chair', xp: 87, level: 14, category: 'Furniture' },
      { name: 'Oak chair', xp: 120 },
      { name: 'Oak shelves 1', xp: 240, level: 23, category: 'Furniture' },
      { name: 'Oak bookcase', xp: 180 },
      { name: 'Oak larder', xp: 480 },
      { name: 'Oak dining table', xp: 240 },
      { name: 'Carved oak table', xp: 360 },
      { name: 'Oak armchair', xp: 180, level: 26, category: 'Furniture' },
      { name: 'Oak bed', xp: 210, level: 30, category: 'Furniture' },
      { name: 'Carved oak magic wardrobe', xp: 360, level: 51, category: 'Storage' },
      { name: 'Teak dining table', xp: 360 },
      { name: 'Teak table', xp: 270 },
      { name: 'Teak armchair', xp: 180, level: 35, category: 'Furniture' },
      { name: 'Teak bed', xp: 300, level: 40, category: 'Furniture' },
      { name: 'Teak larder', xp: 750, level: 43, category: 'Furniture' },
      { name: 'Carved teak bench', xp: 360 },
      { name: 'Teak garden bench', xp: 540 },
      { name: 'Teak wardrobe', xp: 270 },
      { name: 'Mahogany table', xp: 840 },
      { name: 'Mahogany armchair', xp: 280 },
      { name: 'Mahogany bed', xp: 450, level: 53, category: 'Furniture' },
      { name: 'Mahogany prize chest', xp: 860, level: 54, category: 'Furniture' },
      { name: 'Mahogany wardrobe', xp: 420 },
      { name: 'Gnome bench', xp: 840 },
      { name: 'Mahogany bench', xp: 560 },
      { name: 'Mounted mythical cape', xp: 370 },
      { name: 'Mounted glory', xp: 290 },
      { name: 'Mounted xeric\'s talisman', xp: 500, level: 72, category: 'Mounted items' },
      { name: 'Mounted digsite pendant', xp: 250, level: 82, category: 'Mounted items' },
      { name: 'Oak dungeon door', xp: 600 },
      { name: 'Oak treasure chest', xp: 340, level: 48, category: 'Storage' },
      { name: 'Teak magic wardrobe', xp: 540 },
      { name: 'Mahogany magic wardrobe', xp: 840 },
      { name: 'Teak cape rack', xp: 360, level: 63, category: 'Storage' },
      { name: 'Mahogany cape rack', xp: 560, level: 72, category: 'Storage' },
      { name: 'Marble block build', xp: 500 },
      { name: 'Mahogany homes beginner contract', xp: 2_000 },
      { name: 'Mahogany homes novice contract', xp: 3_000 },
      { name: 'Mahogany homes adept contract', xp: 6_000 },
      { name: 'Mahogany homes expert contract', xp: 12_000 }
    ]
  },
  {
    skill: 'Sailing',
    actions: [
      { name: 'Navigation contract', xp: 250 },
      { name: 'Delivery contract', xp: 650 },
      { name: 'Salvage action', xp: 85 },
      { name: 'Charting discovery', xp: 1_200 },
      { name: 'Ship upgrade project', xp: 2_500 },
      { name: 'Sea monster encounter', xp: 1_800 }
    ]
  }
];

export function actionsForSkill(skill: string) {
  return SKILL_ACTIONS.find((group) => group.skill === skill)?.actions || [];
}
