package com.osrstelemetry.telemetry;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;
import net.runelite.client.config.Range;

@ConfigGroup("telemetry")
public interface TelemetryConfig extends Config
{
    @ConfigItem(
        keyName = "apiBaseUrl",
        name = "API Base URL",
        description = "Base URL for the telemetry API"
    )
    default String apiBaseUrl()
    {
        return "http://localhost:3000";
    }

    @ConfigItem(
        keyName = "apiToken",
        name = "API Token",
        description = "Generated by your backend"
    )
    default String apiToken()
    {
        return "";
    }

    @Range(
        min = 15,
        max = 3600
    )
    @ConfigItem(
        keyName = "sendIntervalSeconds",
        name = "Send Interval (seconds)",
        description = "How often to send batched XP changes"
    )
    default int sendIntervalSeconds()
    {
        return 120;
    }
}
